/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GiftCardRouteImport } from './routes/gift-card'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AuthenticatedGestionaleRouteImport } from './routes/_authenticated/gestionale'
import { Route as AuthenticatedGestionaleIndexRouteImport } from './routes/_authenticated/gestionale.index'
import { Route as AuthenticatedGestionaleAgendaRouteImport } from './routes/_authenticated/gestionale.agenda'
import { Route as AuthenticatedGestionaleClientiRouteImport } from './routes/_authenticated/gestionale.clienti'
import { Route as AuthenticatedGestionaleListinoRouteImport } from './routes/_authenticated/gestionale.listino'
import { Route as AuthenticatedGestionalePrenotazioniRouteImport } from './routes/_authenticated/gestionale.prenotazioni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardRoute = GiftCardRouteImport.update({
  id: '/gift-card',
  path: '/gift-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionaleRoute = AuthenticatedGestionaleRouteImport.update({
  id: '/gestionale',
  path: '/gestionale',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestionaleIndexRoute =
  AuthenticatedGestionaleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleAgendaRoute =
  AuthenticatedGestionaleAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleClientiRoute =
  AuthenticatedGestionaleClientiRouteImport.update({
    id: '/clienti',
    path: '/clienti',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionaleListinoRoute =
  AuthenticatedGestionaleListinoRouteImport.update({
    id: '/listino',
    path: '/listino',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)
const AuthenticatedGestionalePrenotazioniRoute =
  AuthenticatedGestionalePrenotazioniRouteImport.update({
    id: '/prenotazioni',
    path: '/prenotazioni',
    getParentRoute: () => AuthenticatedGestionaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/gift-card': typeof GiftCardRoute
  '/prenota': typeof PrenotaRoute
  '/servizi': typeof ServiziRoute
  '/team': typeof TeamRoute
  '/gestionale': typeof AuthenticatedGestionaleRouteWithChildren
  '/gestionale/agenda': typeof AuthenticatedGestionaleAgendaRoute
  '/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/gestionale/listino': typeof AuthenticatedGestionaleListinoRoute
  '/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/gestionale/': typeof AuthenticatedGestionaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/gift-card': typeof GiftCardRoute
  '/prenota': typeof PrenotaRoute
  '/servizi': typeof ServiziRoute
  '/team': typeof TeamRoute
  '/gestionale/agenda': typeof AuthenticatedGestionaleAgendaRoute
  '/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/gestionale/listino': typeof AuthenticatedGestionaleListinoRoute
  '/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/gestionale': typeof AuthenticatedGestionaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/gift-card': typeof GiftCardRoute
  '/prenota': typeof PrenotaRoute
  '/servizi': typeof ServiziRoute
  '/team': typeof TeamRoute
  '/_authenticated/gestionale': typeof AuthenticatedGestionaleRouteWithChildren
  '/_authenticated/gestionale/agenda': typeof AuthenticatedGestionaleAgendaRoute
  '/_authenticated/gestionale/clienti': typeof AuthenticatedGestionaleClientiRoute
  '/_authenticated/gestionale/listino': typeof AuthenticatedGestionaleListinoRoute
  '/_authenticated/gestionale/prenotazioni': typeof AuthenticatedGestionalePrenotazioniRoute
  '/_authenticated/gestionale/': typeof AuthenticatedGestionaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/gift-card'
    | '/prenota'
    | '/servizi'
    | '/team'
    | '/gestionale'
    | '/gestionale/agenda'
    | '/gestionale/clienti'
    | '/gestionale/listino'
    | '/gestionale/prenotazioni'
    | '/gestionale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/gift-card'
    | '/prenota'
    | '/servizi'
    | '/team'
    | '/gestionale/agenda'
    | '/gestionale/clienti'
    | '/gestionale/listino'
    | '/gestionale/prenotazioni'
    | '/gestionale'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/gift-card'
    | '/prenota'
    | '/servizi'
    | '/team'
    | '/_authenticated/gestionale'
    | '/_authenticated/gestionale/agenda'
    | '/_authenticated/gestionale/clienti'
    | '/_authenticated/gestionale/listino'
    | '/_authenticated/gestionale/prenotazioni'
    | '/_authenticated/gestionale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  FaqRoute: typeof FaqRoute
  GiftCardRoute: typeof GiftCardRoute
  PrenotaRoute: typeof PrenotaRoute
  ServiziRoute: typeof ServiziRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-card': {
      id: '/gift-card'
      path: '/gift-card'
      fullPath: '/gift-card'
      preLoaderRoute: typeof GiftCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestionale': {
      id: '/_authenticated/gestionale'
      path: '/gestionale'
      fullPath: '/gestionale'
      preLoaderRoute: typeof AuthenticatedGestionaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestionale/': {
      id: '/_authenticated/gestionale/'
      path: '/'
      fullPath: '/gestionale/'
      preLoaderRoute: typeof AuthenticatedGestionaleIndexRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/agenda': {
      id: '/_authenticated/gestionale/agenda'
      path: '/agenda'
      fullPath: '/gestionale/agenda'
      preLoaderRoute: typeof AuthenticatedGestionaleAgendaRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/clienti': {
      id: '/_authenticated/gestionale/clienti'
      path: '/clienti'
      fullPath: '/gestionale/clienti'
      preLoaderRoute: typeof AuthenticatedGestionaleClientiRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/listino': {
      id: '/_authenticated/gestionale/listino'
      path: '/listino'
      fullPath: '/gestionale/listino'
      preLoaderRoute: typeof AuthenticatedGestionaleListinoRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
    '/_authenticated/gestionale/prenotazioni': {
      id: '/_authenticated/gestionale/prenotazioni'
      path: '/prenotazioni'
      fullPath: '/gestionale/prenotazioni'
      preLoaderRoute: typeof AuthenticatedGestionalePrenotazioniRouteImport
      parentRoute: typeof AuthenticatedGestionaleRoute
    }
  }
}

interface AuthenticatedGestionaleRouteChildren {
  AuthenticatedGestionaleAgendaRoute: typeof AuthenticatedGestionaleAgendaRoute
  AuthenticatedGestionaleClientiRoute: typeof AuthenticatedGestionaleClientiRoute
  AuthenticatedGestionaleListinoRoute: typeof AuthenticatedGestionaleListinoRoute
  AuthenticatedGestionalePrenotazioniRoute: typeof AuthenticatedGestionalePrenotazioniRoute
  AuthenticatedGestionaleIndexRoute: typeof AuthenticatedGestionaleIndexRoute
}

const AuthenticatedGestionaleRouteChildren: AuthenticatedGestionaleRouteChildren =
  {
    AuthenticatedGestionaleAgendaRoute: AuthenticatedGestionaleAgendaRoute,
    AuthenticatedGestionaleClientiRoute: AuthenticatedGestionaleClientiRoute,
    AuthenticatedGestionaleListinoRoute: AuthenticatedGestionaleListinoRoute,
    AuthenticatedGestionalePrenotazioniRoute:
      AuthenticatedGestionalePrenotazioniRoute,
    AuthenticatedGestionaleIndexRoute: AuthenticatedGestionaleIndexRoute,
  }

const AuthenticatedGestionaleRouteWithChildren =
  AuthenticatedGestionaleRoute._addFileChildren(
    AuthenticatedGestionaleRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestionaleRoute: typeof AuthenticatedGestionaleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestionaleRoute: AuthenticatedGestionaleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  FaqRoute: FaqRoute,
  GiftCardRoute: GiftCardRoute,
  PrenotaRoute: PrenotaRoute,
  ServiziRoute: ServiziRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
